name: First workflow
on:
    push:
        branches:
            -   master
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "::warning file=README.md,line=1,col=5::Yo! You're spelling is off or something, you should go ahead and fix that"
        echo """::warning file=README.md,line=1,col=5:: Hello there
        This is some multi-line annotation
        eslint --report-unused-disable-directives --max-warnings=0 . --ext .js,.ts "--format" "./node_modules/eslint-plugin-github/lib/formatters/stylish-fixes.js
        Browserslist: caniuse-lite is outdated. Please run:
        nnpx browserslist@latest --update-db
        """

