name: Env Variables
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    strategy:
      matrix:
        python-version: [ 'pypy2', 'pypy3' ]
    steps:
    - uses: konradpabjan/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - run: python --version
