name: Python Test
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.6']
    name: Python ${{ matrix.python-version }}
    steps:
      - name: output env
        run: printenv
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -c "import sys; import os; print(sys.maxunicode); print(sys.version); print(os.path.dirname(sys.executable))"
        
