on:
    push:
        branches:
            -   master
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [8.x, 10.x, 12.x, 13.x]
    steps:
        - name: 'Create a file'
          run: echo ${{ matrix.node-version }} > my_file.txt
        - name: 'Accidently upload to the same artifact via multiple jobs'
          uses: 'actions/upload-artifact@v2'
          with:
              path: ${{ github.workspace }}       
