name: Env Variables
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, pypy3 ]
        os: [self-hosted]
    steps:
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - run: |
        import sys
        print(sys.version)
