name: Python Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.5', '3.6', '3.7', '3.8', 'pypy2', 'pypy3' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - name: Setup python
        uses: actions/setup-python@konradpabjan/npm-updates
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -c "import sys; print(sys.version)"
