name: Env Variables
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, pypy3 ]
        os: [ubuntu-latest]
    steps:
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - run: python -c "import sys; print(sys.version)"
