name: Env Variables
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 2.7 ]
        os: [ubuntu-latest]
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - run: python -c "import sys; print(sys.maxunicode)"
