on:
    push:
        branches:
            -   master
name: Tests
jobs:
  tests:
    runs-on: ubuntu-latest
    container: ubuntu:19.10
    strategy:
      matrix:
        python: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
