name: First workflow
on:
    push:
        branches:
            -   master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
          printenv
    - uses: actions/upload-artifact@v2
      with:
          name: 'my-artifact'
          path: '~/' 
