name: Env Variables
on: [push]
jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', '3.5', '3.6', '3.7', '3.8', 'pypy2', 'pypy3' ]
    steps:
    - uses: robindaumann/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - run: python --version
