on:
    push:
        branches:
            -   master
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: ./test.sh
      - name: Test stuff
        run: |
            echo "printing something"
            echo "::error::Must supply java version argument"
            throw "some error"
            echo "test again"
            throw "::error::Must supply java version argument"
        shell: pwsh
            
            
