name: Python Test
on: [push]
jobs:
  example:
    runs-on: [ubuntu-latest]
    env:
      input: environment variable
    steps:
    - name: Get Env Variable
      uses: konradpabjan/GetActionsEnvVariableFromNodeContext@master
      with:
        EnvName: ACTIONS_RUNTIME_URL
      id: get_runtime_url
    - name: Output Env Variable
      run: |
        echo ${{ steps.get_runtime_url.outputs.EnvValue }}
