on:
    push:
        branches:
            -   master
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: ./test.sh
            
            
