name: Python Test
on: [push]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.8']
    name: Python ${{ matrix.python-version }}
    steps:
      - name: output env
        run: printenv
      - name: Setup python
        uses: konradpabjan/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -c "import sys; print(sys.maxunicode)"
        
