name: Python Test
on: [push]
jobs:
  example:
    runs-on: [ubuntu-latest]
    env:
      input: environment variable
    steps:
    - name: Get Runtime URL
      uses: actions/setup-python@master
      with:
        python-version: 2.7
    - run: python -c "import sys; print(sys.maxunicode)"
