name: Python Testing
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "pypy3"
      - name: Import lzma
        run: python -c "import lzma"
