name: Python Test
on: [push]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.5']
    name: Python ${{ matrix.python-version }}
    steps:
      - name: output env
        run: printenv
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -c "import sys; print(sys.maxunicode) print(sys.version)"
        
