name: Env Variables
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
        os: [self-hosted]
    steps:
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - run: python -c "import sys; print(sys.version)"
    - run: |
        cd C:\hostedtoolcache\windows\Python\3.7.6\x64
        ls
