name: Reusable

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Call Reusable 1
      uses: konradpabjan/reusable-workflow-test/.github/workflows/blank.yml@main
    - name: Call Reusable 2
      uses: konradpabjan/reusable-workflow-test/.github/workflows/blank.yml@main
