on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types: 
      - completed
      - requested
name: workflow_run test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "hello"
