name: Rename

on: [pull_request, workflow_dispatch]

jobs:
 build:
   runs-on: ubuntu-latest
   environment: 
      name: testing-env
      url: "https://github.com/konradpabjan"
   steps:
     - uses: actions/checkout@v2
     - name: Setup java
       uses: actions/setup-java@v2
       with:
         distribution: 'adopt'
         java-version: 11
 
