name: Summaries

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest 
    steps:
    - name: Adding markdown
      run: |
        echo "The build failed! :x: " >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Run the following command locally and commit the changes" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo 'npm run format' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
