name: Second workflow
on:
  workflow_run:
    workflows: ["First workflow"]
    branches: [master]
    types: 
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        printenv
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/download-artifact@v2
      name: 'Download from another workflow'
      with:
          name: 'my-artifact'
