name: Testing2
on:
    workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "::warning file=README.md,line=1,col=5::Yo! You're spelling is off or something, you should go ahead and fix that"
      shell: bash
