name: Second workflow
on:
  workflow_run:
    workflows: ["First workflow"]
    branches: [master]
    types: 
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "hello"
