name: Notifications

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
jobs:
  # This workflow contains a single job called “build”
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: preflight
    steps:
      - uses: actions/checkout@v2
        with:
          state: pending
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test:
    runs-on: ubuntu-latest
    environment:
      name: dogfood
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy:
      runs-on: ubuntu-latest
      environment:
        name: prod
      steps:
        - uses: actions/checkout@v2
        - name: Run a one-line script
          run: echo Hello, world!
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
