name: multi-platform-build

on: pull_request

jobs:
 ios-build:
   runs-on: ubuntu-latest
   steps:
     - run:
         for ((i = 0 ; i < 200 ; i++)); do echo "Hello Friend"; done
       shell: bash
 
