on:
  workflow_run:
    workflows: ["python.yml"]
    branches: [main]
    types: 
      - completed
      - requested
name: Testing
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "hello"
