name: Summaries

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest 
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ::error:: hi there
          echo ::warning:: this is a warning
          
      - name: composite action test
        uses: konradpabjan/composite-action-test@main
